name: Tests

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.6', '3.7', '3.8' ]
        db: [ postgres, mysql, sqlite ]
        django: [ '22', '31', '32' ]
    name: django-${{ matrix.django }}, python${{ matrix.python }}, ${{ matrix.db }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install test dependencies
        run: |
          pip install tox codecov
          sudo apt-get update && sudo apt-get install libpq-dev libmysqlclient-dev
      - name: Run tests
        run: tox
        env:
          TOXENV: django${{ matrix.django }}-${{ matrix.db }}
          DB: ${{ matrix.db }}
      - name: Report coverage
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  tests-live:
    runs-on: ubuntu-latest
    name: live
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"
          architecture: x64
      - name: Install test dependencies
        run: |
          pip install tox codecov
          sudo apt-get update && sudo apt-get install libpq-dev
      - name: Run tests
        run: tox
        env:
          TOXENV: live
          DB: postgres
      - name: Report coverage
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
